services:
  discord-bot:
    container_name: ruhi-nyan-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/bot
    stdin_open: true
    tty: true
    command: bun run dev