version: "3"
services:
  ruhinyan:
    container_name: ruhinyan
    restart: always
    image: ruhinyan
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
